# Generated by Django 2.2 on 2020-10-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
